apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-latam-api-sns-publisher
  namespace: {{ .Values.env.namespace }}
  labels:
    app: {{ .Release.Name }}-latam-api-sns-publisher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-latam-api-sns-publisher
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-latam-api-sns-publisher
    spec:
      containers:
        - name: latam-api-sns-publisher
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-secret
                  key: AWS_DEFAULT_REGION
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      imagePullSecrets:
        - name: secretdocker
      imagePullSecrets:
        - name: aws-credentials-secret
