apiVersion: v1
kind: Secret
metadata:
  name: secretdocker
  namespace: {{ .Values.env.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX