apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-secret
  namespace: {{ .Values.env.namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXX
  AWS_DEFAULT_REGION: XXXXXXXX
