apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-latam-api-sns-publisher
  namespace: {{ .Values.env.namespace }}
  labels:
    app: {{ .Release.Name }}-latam-api-sns-publisher
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8010
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-latam-api-sns-publisher
