services:
  latam_sns_publisher:
    build: .
    container_name: latam_sns_publisher
    environment:
      - AWS_ACCESS_KEY_ID=111111111111
      - AWS_SECRET_ACCESS_KEY=111111111111111111111111
      - AWS_DEFAULT_REGION=us-east-2
    command: "uvicorn publicador:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8002:8000"
